DEFAULT_NAME = "TP-Link Router"
DOMAIN = "tplink_router"
CONF_CLIENT_CLASS = "client_class"
CONF_SUPPORT_VPN = "support_vpn"
CONF_SUPPORT_TRACKER = "support_tracker"
DEFAULT_USER = "admin"
DEFAULT_HOST = "http://192.168.0.1"

EVENT_NEW_DEVICE = f"{DOMAIN}_new_device"
EVENT_ONLINE = f"{DOMAIN}_device_online"
EVENT_OFFLINE = f"{DOMAIN}_device_offline"
EVENT_NEW_SMS = f"{DOMAIN}_new_sms"
