send_sms:
  fields:
    number:
      required: true
      selector:
        text:
    text:
      required: true
      selector:
        text:
    device:
      required: true
      selector:
        device:
          integration: tplink_router

add_reservation:
  fields:
    device:
      required: true
      selector:
        device:
          integration: tplink_router
    mac:
      required: true
      selector:
        text:
    ip:
      required: true
      selector:
        text:
    comment:
      required: false
      selector:
        text:
    enable:
      default: true
      selector:
        boolean:

delete_reservation:
  fields:
    device:
      required: true
      selector:
        device:
          integration: tplink_router
    mac:
      required: true
      selector:
        text:
